### ISSUE TITLE
Feature Request: Go to definition.

### ISSUE THREAD

**Issue by muhajirdev** [UnwrittenFun/svelte-language-server#15]
Hi there,

Great plugin. Is there a plan to support "go to definition"?

**Comment by UnwrittenFun** [comment]
added in 8e205765a0c47e4b1a4eff02e94068bac660c312

**Comment by muhajirdev** [comment]
Thanks @UnwrittenFun

**Comment by muhajirdev** [comment]
Hey,
I am trying to test this feature. But it doesn't seems to be working. Perhaps I missed some config? 

Related: https://github.com/UnwrittenFun/svelte-vscode/issues/53.
