### ISSUE TITLE
coc.nvim issues

### ISSUE THREAD

**Issue by vlad-terin** [UnwrittenFun/svelte-language-server#24]
Configured coc.nvim plugin with svelte-language-server. Everything works fine - it's running in coc services. 

However, basic js completions don't work, like Math.cos doesn't find the methods, can't jump to definitions, etc. Compared to vetur it was working out of the box. 

```
"languageserver": {
  "svelte": {
    "module": "/path/to/npm-global/bin/server.js",
    "filetypes": ["html", "svelte"],
    "trace.server": "verbose"
  }
}
```

**Comment by soywod** [comment]
https://github.com/UnwrittenFun/svelte-language-server/blob/723310cfaefeb5aff0d4c769e79127eecea96117/src/plugins/TypeScriptPlugin.ts#L55-L59

The completion is not enabled by default. I added `completions: {enable: true}` and it works fine. Is there any reason why it's disabled by default?

**Comment by vlad-terin** [comment]
Thank you good sir! Works great for me.
