### ISSUE TITLE
Typescript does not work

### ISSUE THREAD

**Issue by ilajosmanov** [UnwrittenFun/svelte-language-server#26]
If I wanna set type explicitly — I look next error `parse-error`

<img width="755" alt="Screen Shot 2019-09-06 at 09 29 36" src="https://user-images.githubusercontent.com/18512404/64405925-1f8de280-d089-11e9-814b-28160875bc94.png">

**Comment by UnwrittenFun** [comment]
Please refer to https://github.com/UnwrittenFun/svelte-vscode/blob/master/docs/preprocessors/typescript.md for typescript setup
