### ISSUE TITLE
Language server crashes silently

### ISSUE THREAD

**Issue by Andilutten** [UnwrittenFun/svelte-language-server#29]
After install with 
```
sudo npm i -g svelte-language-server
```
the command svelteserver runs for a second and kills itself silently.

Has anyone else had this issue ? 

Im running on Ubuntu 19.04
with node 12.10

**Comment by UnwrittenFun** [comment]
I must admit, i've not tried running it standalone, and currently that bin expects to talk over IPC so I would imagine running it from the commandline wouldn't work right now.

What were you expecting/hoping would happen when running it. An http server perhaps? Let me know 🙂

**Comment by Andilutten** [comment]
@UnwrittenFun Sorry for not answering , this thread got lost on me.

Maybe expose a stdio interface ? Don't quote me on it but im pretty sure atleast gopls does something like this
