### ISSUE TITLE
VS Code Error Messages in Output

### ISSUE THREAD

**Issue by stevesob** [UnwrittenFun/svelte-language-server#30]
I constantly get these messages in VS Code Output and the screen switches to the output screen when it happens. Quite annoying. Any ideas on how to fix?

[Error - 11:57:04 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 11:59:35 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 12:00:02 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 12:00:19 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 12:00:53 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603

**Comment by UnwrittenFun** [comment]
Are you able to provide a code snippet that triggers this error?

As for the output panel popping up on every error, that _should_ have been fixed 0.9.1 of the vscode plugin, what version are you running?
