### ISSUE TITLE
"Rename Symbol" feature doesn't work

### ISSUE THREAD

**Issue by hexrcs** [UnwrittenFun/svelte-language-server#31]
When the cursor is placed on a symbol (variable/function name), pressing <kbd>F2</kbd> in VS Code on macOS should be able to let the user rename the symbol throughout the project.

This feature currently doesn't work for a `.svelte` file. Nothing happens when <kbd>F2</kbd> is pressed.

**Comment by UnwrittenFun** [comment]
Moved this to the language server repo as a feature request

**Comment by hexrcs** [comment]
@UnwrittenFun Thanks for transferring this issue. If no one is not interested, I'd like to give it a try to implement this. 😃

**Comment by UnwrittenFun** [comment]
@hexrcs That would be great

You would likely need to add handling for the rename request [(spec)](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_rename).

Probably the easiest/quickest implementation would be to essentially forward the request to TypeScript to handle. In which case you would need to add it to [TypeScriptPlugin.ts](https://github.com/UnwrittenFun/svelte-language-server/blob/bcbed98ddc309678e2c37af945f5409e562313c1/src/plugins/TypeScriptPlugin.ts). As we've not dealt with this before you would also need to add a wrapper for it in [wrapFragmentPlugin.ts](https://github.com/UnwrittenFun/svelte-language-server/blob/bcbed98ddc309678e2c37af945f5409e562313c1/src/api/wrapFragmentPlugin.ts) and handle the event in [server.ts](https://github.com/UnwrittenFun/svelte-language-server/blob/bcbed98ddc309678e2c37af945f5409e562313c1/src/server.ts).

Downside of that implementation is it wouldn't rename any symbols used in templates.

**Comment by hexrcs** [comment]
@UnwrittenFun Thanks a lot! I'll try that first.

**Comment by pushkine** [comment]
hey @UnwrittenFun 
I'd really like to get this feature for svelte, I thereby spent a few hours getting familiar with developing vscode language extensions yesterday before trying my luck on this repository, sadly it appears that it doesn't follow the exact same structure as the tutorial, could you document a straightforward way to get a local clone of the extension to run a local clone of the language server in a debug vscode window ?
