### ISSUE TITLE
How can I use this as a language server similar to typescript-language-server?

### ISSUE THREAD

**Issue by JoshuaJWilborn** [UnwrittenFun/svelte-language-server#32]
For instance to use typescript-language-server, I can call it with `typescript-language-server --stdio`, and then communicate messages via stdio.  Is such an interface provided?

**Comment by Axelen123** [comment]
No but [this](https://github.com/glean-dev/svelte-language-server/commit/a8ea58200baf175a31c17010a9ddc2f678e9ed1e#diff-916156c481141bfcd08c6ae40ce10e00) fork does.

**Comment by pappasam** [comment]
@UnwrittenFun would you be able to release a new version with support for STDIO? I see that you made a commit three months ago with this feature but simply haven't bumped the version on npm. Any reason why we're holding back?
