### ISSUE TITLE
[ts 6133] [H] 'variable' is declared but its value is never read.

### ISSUE THREAD

**Issue by kanmii** [UnwrittenFun/svelte-language-server#39]
Thanks for the awesome package. I'm using typescript and everything is working fine except I am getting the error `[ts 6133] [H] 'variable' is declared but its value is never read`. I have provided a [sample repo](https://github.com/kanmii/svelte-typescript-example).
![Screenshot from 2019-12-16 12-57-52](https://user-images.githubusercontent.com/1783751/70905427-1dcaa800-2004-11ea-99fe-6a130ed4dc2a.png)

**Comment by kanmii** [comment]
Ok, it is related to vscode plugin.

**Comment by pipex** [comment]
I've been having the same issue, but coc-svelte in nvim. Did you manage to fix it?
