### ISSUE TITLE
Cannot disable default `css` and `js` validators

### ISSUE THREAD

**Issue by kaisermann** [UnwrittenFun/svelte-language-server#9]
Related to https://github.com/UnwrittenFun/svelte-vscode/issues/21

Should it respect the `javascript.validate.enable` and `css.validate.enable`?

**Comment by kaisermann** [comment]
Maybe it could be `svelte.validate.scripts` and `svelte.validate.styles` 🤔

**Comment by UnwrittenFun** [comment]
this has been added in v0.5.0

you can disable almost everything.

e.g. this would disable just the diagnostics part of the typescript smarts
```json
{
  "svelte.plugin.typescript.diagnostics.enable": false
}
```

and this would disable it all (hover, formatting, etc)
```json
{
  "svelte.plugin.typescript.enable": false
}
```

**Comment by droidMakk** [comment]
![image](https://user-images.githubusercontent.com/20293708/79354008-75990180-7f59-11ea-956d-2d213e365096.png)
![image](https://user-images.githubusercontent.com/20293708/79354047-80ec2d00-7f59-11ea-9af0-256a34e79941.png)

I've disabled everything related to CSS but still getting this.
